version: '3'

x-common-env: &common-env
    APACHE_RUN_USER: "www-data"
    APACHE_RUN_GROUP: "www-data"
    APACHE_LOG_DIR: /var/log/apache2
    APACHE_RUN_DIR: /var/run/apache2
    APACHE_PID_FILE: /var/run/apache2/apache2.pid
    APACHE_LOCK_DIR: /var/lock/apache2

services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        environment:
            <<: *common-env
            DB_HOST: db
        volumes:
            - ./:/var/www/html
        networks:
            - laravel-net
        depends_on:
            - db
        entrypoint: sh -c "apache2 -D FOREGROUND"

    db:
        container_name: db
        image: mysql:8.0
        ports:
            - "${DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel-net

networks:
    laravel-net:
        driver: bridge

volumes:
    db_data:
